### ISSUE TITLE
Error while using the complex_dotplot_single() function

### ISSUE THREAD

**Issue by aditisk** [HaojiaWu/plot1cell#2]
Hi @HaojiaWu,

Thank you so much for developing this package with the new plotting capabilities. I am trying to follow the tutorial and running into an error. I have a very large seurat object so I subsetted the object before trying to plot. My code is pasted below with the error message:

#Saving the plot since I keep getting an error in RStudio to plot in the plotting window
ggsave(complex_dotplot_single(cd8, feature = "HAVCR2",groups = cd8@meta.data$Treatment,splitby = "Timepoint"),"test.png",device = "png")

##Error is pasted below
Warning: Found the following features in more than one assay, excluding the default. We will not include these in the final data frame: HAVCR2
Warning: Could not find RELA in the default search locations, found in RNA assay instead
Error in names(x) <- value : 
  'names' attribute [36604] must be the same length as the vector [3]
In addition: Warning message:
In FetchData.Seurat(new_seu, slot = data.type, vars = c(features,  :
  The following requested variables were not found: HAVCR2, NIVO, IPI

Please let me know if I am missing something that is triggering this error. If I use the same command without the "splitby" argument, it works just fine, and I am able to generate the plot.

Thanks a lot.

**Comment by HaojiaWu** [comment]
Thanks for your interest in using our package. Can you try the codes below? Note that the ```groups``` argument should be the column name in your Seurat metadata (not the actual values in the column). 
```r
png(filename =  'test.png', width = 4, height = 6, units = 'in', res = 300)
complex_dotplot_single(cd8, feature = "HAVCR2", groups = "Treatment", splitby = "Timepoint")
dev.off()
```

**Comment by aditisk** [comment]
Thank you so much, the code above works - specifying the column names was the part I was doing wrong.
